version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.6
        environment:
          CIRCLE_PROJECT_REPONAME: go-pkgs
    working_directory: ~/go/src/github.com/iotexproject/go-pkgs
    steps:
      - checkout
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - ~/go/src/github.com/iotexproject/go-pkgs/vendor
      - run:
          name: "get vendor"
          command: |
            export GOPATH=~/go
            if [ ! -d ~/go/src/github.com/iotexproject/go-pkgs/vendor ]; then
                # dep init
                dep ensure
            fi
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
              - ~/go/src/github.com/iotexproject/go-pkgs/vendor
      - run:
          name: go test
          command: |
            export GOPATH=~/go
            #go get -v -t -d ./...
            set -e
            for d in $(go list ./...|grep -v vendor); do
              go test -short -v -coverprofile=profile.out -covermode=count "$d"
              if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
              fi
            done
